# Generated by Django 3.1.3 on 2020-11-19 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cuisine', models.CharField(choices=[('1', 'American'), ('2', 'Breakfast'), ('3', 'Chinese'), ('4', 'Coffee'), ('5', 'Pizza')], max_length=1)),
                ('totalReviews', models.IntegerField(default=0)),
            ],
        ),
    ]
