# Generated by Django 3.1.3 on 2020-11-22 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('1', 'American'), ('2', 'Breakfast'), ('3', 'Chinese'), ('4', 'Cafe'), ('5', 'Italian'), ('6', 'Mexican'), ('7', 'Bars'), ('8', 'Fast Food'), ('9', 'Ramen'), ('10', 'Buffet'), ('11', 'Thai'), ('12', 'Steakhouse'), ('13', 'Japanese'), ('14', 'Greek'), ('15', 'Indian'), ('16', 'Korean')], max_length=2),
        ),
    ]
