# Generated by Django 2.0.7 on 2020-11-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('description', models.TextField()),
                ('numReviews', models.IntegerField(default=0)),
            ],
        ),
    ]
