# Generated by Django 3.1.3 on 2020-12-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20201201_2156'),
        ('restaurants', '0002_auto_20201122_1656'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='dish',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dishes.dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
            preserve_default=False,
        ),
    ]
